### ISSUE TITLE
lorri internal stream-event fails with varlinkerror

### ISSUE THREAD

**Issue by symphorien** [nix-community/lorri#4]
**Describe the bug**
lorri internal stream-events is broken with the following error
```console
$  lorri internal stream-events     
Feb 21 15:03:26.288 ERRO Varlink(src/com_target_lorri.rs:78: Varlink_Error
Caused by:
/build/lorri-1.2-vendor.tar.gz/varlink/src/lib.rs:1128: InterfaceNotFound("com.target.lorri"))

```

**Metadata**
Nothing interesting in journalctl.

```console
$  lorri info --shell-file shell.nix
lorri version: 1.2
GC roots exist, shell_gc_root: "/home/symphorien/.cache/lorri/gc_roots/d01b506259718b2a7903535c864b1593/gc_root/shell_gc_root"

```

```console
$ uname -a
Linux bete 5.9.16 #1-NixOS SMP Mon Dec 21 12:28:21 UTC 2020 x86_64 GNU/Linux
```

**Additional context**
Installed lorri with the home-manager module.

**Motivation for using lorri internal**: see https://github.com/target/lorri/issues/365#issuecomment-606835166

**Comment by Profpatsch** [comment]
Did you update your client to master?

I changed the interface to be `org.nix-community.lorri`, and if you are still using a daemon with the old interface it will break.

**Comment by symphorien** [comment]
Still happens on 516d91adf291c51dcd5be23342107e352f4934a7:
```
$  lorri internal stream-events
Mar 04 21:20:20.842 ERRO Varlink(src/org_nixos_lorri.rs:78: Varlink_Error
Caused by:
/build/lorri-1.3-vendor.tar.gz/varlink/src/lib.rs:1128: InterfaceNotFound("org.nixos.lorri"))
```

**Comment by Profpatsch** [comment]
Crap, I forgot to update one interface name. My bad.

**Comment by Profpatsch** [comment]
Update: I updated the interface name, but it’s still throwing the error. Unsure.
