### ISSUE TITLE
Mark the upstream change in target/lorri

### ISSUE THREAD

**Issue by Profpatsch** [nix-community/lorri#40]
We moved the repo but the target one is still not marked as out of date.

**Comment by Mathnerd314** [comment]
Does anyone have commit access to the target repo? Just editing the README would clear up a lot of the confusion...

**Comment by Profpatsch** [comment]
I have access. @Mathnerd314 do you want to prepare a PR? it was on my TODO, but there’s a lot going on at the moment so I am not able to spend much time on lorri.

**Comment by Mathnerd314** [comment]
Well I finally got around to thinking about this and it's already done... https://github.com/target/lorri/commit/f3ac576d660ceb587d7692a993088cf78e881fc0. Thanks!

**Comment by Profpatsch** [comment]
Yep!
