### ISSUE TITLE
Cannot write to file with shellHook

### ISSUE THREAD

**Issue by winston0410** [nix-community/lorri#69]
**Describe the bug**
I am trying to write to a file from the `shellHook`.

```nix
{...}:
pkgs.mkShell {
  shellHook = ''
    echo "hello" >> $HOME/hello
  '';
}
```

And I cannot find the file after I have entered the dir.

I have tried this example from [this issue](https://github.com/target/lorri/issues/7), which the hook is running.

```nix
with import <nixpkgs> {};

mkShell {
  shellHook = ''
  export FOO=BAR
  '';
}
```

**To Reproduce**

1. `lorri init`
2. `direnv allow`
3. Paste the code in
```nix
{...}:
pkgs.mkShell {
  shellHook = ''
    echo "hello" >> $HOME/hello
  '';
}
```
4. Exit and enter again, and check for output

**Expected behavior**
I expect it will generate a file in `$HOME/hello`

**Metadata**

```console
$ lorri info
`lorri info --shell-file ./shell.nix`
lorri version: 1.5
GC roots do not exist. Has the project been built with lorri yet?

This is weird. I have built it by exiting  and entering more than once. Not sure if there is any insight from this output
```

```console
$ uname -a
Linux nixos 5.14.3 #1-NixOS SMP Sun Sep 12 07:01:00 UTC 2021 x86_64 GNU/Linux
```

**Additional context**

**Comment by nyarly** [comment]
The current version of Lorri in now 1.7.0, which is in nixpkgs as of NixOS 24.05. Thank you for your patience!
