### ISSUE TITLE
lorri Crash Report

### ISSUE THREAD

**Issue by chrisandreae** [nix-community/lorri#80]
**Describe the bug**

The lorri daemon crashed, yielding the attached crash report from three threads:

**Metadata**

[reports.zip](https://github.com/nix-community/lorri/files/8183325/reports.zip)

```console
$ lorri info --shell-file shell.nix
lorri version: 1.5
GC roots exist, shell_gc_root: /Users/chris/Library/Caches/com.github.nix-community.lorri.lorri.lorri/gc_roots/d44ed7205e17d524d463782543f64e72/gc_root/shell_gc_root
```

```console
$ uname -a
Darwin ume.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64 i386 Darwin
```

**Comment by nyarly** [comment]
This bug is fixed in 1.7.0, which is in nixpkgs as of NixOS 24.05. Thank you for your patience!
