### ISSUE TITLE
Question: can I rid the right-side message?

### ISSUE THREAD

**Issue by hedefalk** [nix-community/lorri#81]
**Feature description**

When I paste cli logs I feel it's a bit annoying with the `lorri-keep-env-hack-nix-shell`:

```
🐟 file -I ~/Downloads/report.csv                                                                          lorri-keep-env-hack-nix-shell 
/Users/viktor/Downloads/report.csv: application/csv; charset=utf-8
```

Using fish. Have I missed some easy setting to rid this?

**Comment by nyarly** [comment]
Where is `lorri-keep-env-hack-nix-shell` coming from in the first place? I'd imagine somewhere in your `fish_prompt.fish`?

**Comment by hedefalk** [comment]
It's the derivation name - the string itself seems to come from here:

https://github.com/nix-community/lorri/blob/b84602c7132293e23eb8957ba493f188ce89ea1c/src/logged-evaluation.nix#L58

**Comment by hedefalk** [comment]
Ah, it's any-nix-shell that puts it there:

https://github.com/haslersn/any-nix-shell#customization

**Comment by hedefalk** [comment]
I revisited this now and I had two other tools involved:

* any-nix-shell
* staryship.rs

Both _default_ settings printed this derivation name as part of my prompt:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/116520/162279535-d21b257c-2329-48b6-acb8-0dec9d44a3d4.png">

I can config both away with the side-effect of not seeing this info when I might want to, like on a manual nix-shell. The name is just a little annoying…? Maybe just "lorri"?

**Comment by hedefalk** [comment]
The green thing is any-nix-shell which I could rid by removing `--info-right`. The blue one I had already config'ed away from starship.rs default settings https://starship.rs/config/#nix-shell
